### ISSUE TITLE
SetFuel trouble at spawn / update

### ISSUE THREAD

**Issue by zf-development** [CodineDev/cdn-fuel#49]
**Describe the bug**
When the car is started / spawned / entered for the first time / fuel updated it does the backing like when you have no fuel.

**To Reproduce**
1. Spawn the car from a garage
2. Press on the gas

**Expected behavior**
The car will start to go backwards.

**Screenshots | Video**
https://youtu.be/oe40KnScpKc

**Comment by Mitch-Altman** [comment]
Did you mass searched for your old fuel export such as 'LegacyFuel' and replaced them all with 'cdn-fuel' ?

**Comment by zf-development** [comment]
I was using cdn-fuel 2.0.0 before updating.

**Comment by dnelyk** [comment]
Issue described should be fixed in the latest patch!

**Comment by zf-development** [comment]
Why not add the "toggleEngine()" in this?
Like this so there is no changes required?

```lua
CreateThread(function()
    while true do
        Wait(0)
        -- Disable vehicle turning on when pressing W while the car is off.
        local veh = GetVehiclePedIsIn(PlayerPedId(), false)
        if IsPedInVehicle(PlayerPedId(), veh, false) and (GetIsVehicleEngineRunning(veh) == false) or GetFuel(veh) == 0 then
            DisableControlAction(0, 71, true)
        elseif IsPedInVehicle(PlayerPedId(), veh, false) and (GetIsVehicleEngineRunning(veh) == true) and GetFuel(veh) ~= 0 then
            EnableControlAction(0, 71, true)
        end
    end
end)
```

**Comment by dnelyk** [comment]
> Why not add the "toggleEngine()" in this? Like this so there is no changes required?
> 
> ```lua
> CreateThread(function()
>     while true do
>         Wait(0)
>         -- Disable vehicle turning on when pressing W while the car is off.
>         local veh = GetVehiclePedIsIn(PlayerPedId(), false)
>         if IsPedInVehicle(PlayerPedId(), veh, false) and (GetIsVehicleEngineRunning(veh) == false) or GetFuel(veh) == 0 then
>             DisableControlAction(0, 71, true)
>         elseif IsPedInVehicle(PlayerPedId(), veh, false) and (GetIsVehicleEngineRunning(veh) == true) and GetFuel(veh) ~= 0 then
>             EnableControlAction(0, 71, true)
>         end
>     end
> end)
> ```

This is for you to put into your engine toggle command to make sure the vehicle has fuel in the vehicle before turning it on. It does not really have much to do with the fuel script as the toggle engine function is handled inside various locations depending on the server. Usually, it is in qb-vehiclekeys, but if you use ps-hud, it is there instead. It is all based on the end user. But, if you do not install it, the client will not be able to drive on 0 anyway, because of the thread you mentioned above. It just provides some more realism, to where the vehicle cannot turn on if there is no fuel, and it is mainly for electric vehicles.
