### ISSUE TITLE
Missing Credits

### ISSUE THREAD

**Issue by MonkeyWhisper** [CodineDev/cdn-fuel#52]
Where are the credits for Project Sloth ps-fuel?

**Comment by cdnKasu** [comment]
Hey there, you made it abundantly clear we were not welcome in your community. You have been childish and ignoring any attempt we have made to figure out your dislike for us. We were originally given the green light to post this resource built off the original PS-Fuel script. Since then we have completely overhauled it and removed all the PS-Fuel code that was added. The only bits of code left are original LegacyFuel code (Which is also soon going to be changed). 

We hate that this has to be a highschool styled back and fourth and would appreciate some maturity and handling whatever your distaste for us is, privately. We wish you the best of luck in continuing to replicate our ideas in your next PS-Fuel update.

**Comment by MonkeyWhisper** [comment]
I'm not sure where the notion that we dislike you came from, but as we're on the subject:

In the future, consider creating an original READ ME rather than duplicating ours.

Given the limited number of commits you've made, it seems a significant portion of code remains from ps-fuel.

However, worry not, the GLPV3 license offers numerous benefits, including the inspiration and convenience of, if we wanted copying and pasting new features. 

Wishing you the best of luck!

**Comment by cdnKasu** [comment]
Hello once again Mr. Monkey! Always a pleasure seeing you around.

We did use your formatting of the readme because it looks quite nice.

You must not have read the code as well if you think there is still "a significant portion" of code from PS-Fuel still in the script.

We got the idea you dislike us from the fact any mention of CDN-Fuel in your discord warrants a direct warning from you and deletion of the message / thread. The attempt to reach out to you to find out what was wrong, and informing you we will stay out of your community as we see we aren't wanted, was ignored.

Lastly, you're quite right on the licensing! Feel free to continue hitting CTRL + C and CTRL + V on our features as we have a lot more in the works. Maybe finally Project Sloth will release something they have planned.
