### ISSUE TITLE
Multi-Syphon

### ISSUE THREAD

**Issue by LowestCarb** [CodineDev/cdn-fuel#53]
**Describe the bug**
Multiple people can syphon the same vehicle at the same time.
If the vehicle only has 10L left of gas, everyone gets 10L from it.

**To Reproduce**
1. Spawn a vehicle
2. Bring a second person to the vehicle with you
3. Both of you try to syphon at the same time (or close to the same time)
4. Both people will receive the same amount of gas from the vehicle, but the vehicle will lost gas from 1 person.

**Expected behavior**
Only one person should be able to syphon or refuel at a time

**Screenshots | Video**
If applicable, add screenshots or video to help explain your problem.

**Additional context**
Just trying to avoid powergaming.

**Comment by dnelyk** [comment]
I will look into this and get this issue handled as fast as possible.

**Comment by imtorchedbud** [comment]
<3 will let you know if I make any progress

**Comment by dnelyk** [comment]
> <3 will let you know if I make any progress

Issue should be fixed with the latest update; Added a check to make sure that the vehicle has enough fuel to be siphoned from before the fuel is given to the client. So, if two people do it at the same time, and one person takes the fuel, if the vehicle doesn't have, for example, 10 liters left, it will not give the second person who did it the fuel as well.
